version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Berlin
  ignore:
  - dependency-name: "@zeit/next-css"
    versions:
    - ">= 1.0.a"
    - "< 1.1"
