files:
  - source: /lang/en.json
    translation: /lang/%two_letters_code%.json
  - source: /static/**/*.html
    ignore:
      - '*.test.html'
      - '*.fr.html'
      - '*.es.html'
      - '*.ja.html'
      - '*.ru.html'
      - '*.zh.html'
      - '*.pt.html'
      - '*.it.html'
    translation: /%original_path%/%file_name%.%two_letters_code%.html
