name: Setup project
description: Installs the right node version and dependencies
inputs:
  # NOTE: not used since moving to pnpm
  CACHE_VERSION:
    description: The cache version, to manually invalidate the dependencies cache
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: CYPRESS_INSTALL_BINARY=0 pnpm install --shamefully-hoist
